# Generated by Django 5.1.7 on 2025-03-16 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeatBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('picture', models.ImageField(upload_to='profile_pics/')),
                ('aadhar_number', models.CharField(max_length=12, unique=True)),
                ('aadhar_front', models.ImageField(upload_to='aadhar_pics/')),
                ('aadhar_back', models.ImageField(upload_to='aadhar_pics/')),
                ('address', models.TextField()),
                ('shift', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('student_id', models.CharField(blank=True, max_length=20, unique=True)),
            ],
        ),
    ]
