# Generated by Django 5.1.7 on 2025-03-16 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
    ]
