# Generated by Django 5.1.7 on 2025-03-16 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_auto_20250316_1206'),
    ]

    operations = [
    ]
