# Generated by Django 5.1.7 on 2025-03-16 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0005_auto_20250316_1220'),
    ]

    operations = [
    ]
