# Generated by Django 5.1.7 on 2025-03-16 06:56

import django.core.validators
import library_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0006_auto_20250316_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatbooking',
            name='aadhar_back',
            field=models.ImageField(upload_to=library_app.models.SeatBooking.aadhar_back_upload_path),
        ),
        migrations.AlterField(
            model_name='seatbooking',
            name='aadhar_front',
            field=models.ImageField(upload_to=library_app.models.SeatBooking.aadhar_front_upload_path),
        ),
        migrations.AlterField(
            model_name='seatbooking',
            name='aadhar_number',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Aadhar number must be 12 digits.', regex='^\\d{12}$')]),
        ),
        migrations.AlterField(
            model_name='seatbooking',
            name='phone',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='seatbooking',
            name='picture',
            field=models.ImageField(upload_to=library_app.models.SeatBooking.profile_upload_path),
        ),
        migrations.AlterField(
            model_name='seatbooking',
            name='shift',
            field=models.CharField(choices=[('Morning', 'Morning Shift'), ('Afternoon', 'Afternoon Shift'), ('Evening', 'Evening Shift')], max_length=50),
        ),
        migrations.AlterField(
            model_name='seatbooking',
            name='student_id',
            field=models.CharField(blank=True, editable=False, max_length=30, unique=True),
        ),
    ]
